# -*- coding: utf-8 -*-

"""
/***************************************************************************
 AGSTools
                                 A QGIS plugin
 This plugin parses an AGS file and creates a database from it
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-04-19
        copyright            : (C) 2025 by Oliver Burdekin / burdGIS
        email                : info@burdgis.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Oliver Burdekin / burdGIS'
__date__ = '2023-04-19'
__copyright__ = '(C) 2025 by Oliver Burdekin / burdGIS'


# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.PyQt.QtCore import QCoreApplication, QSettings, QVariant
from qgis.core import (QgsApplication,
                       QgsSettings,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterEnum,
                       QgsProcessingParameterFile,
                       QgsProcessingParameterFileDestination,
                       QgsProcessingParameterBoolean,
                       QgsProcessingParameterCrs,
                       QgsProcessingParameterString,
                       QgsCoordinateReferenceSystem,
                       QgsVectorLayer,
                       QgsRasterLayer,
                       QgsField,
                       QgsFields,
                       QgsFeature,
                       QgsGeometry,
                       QgsPointXY,
                       QgsVectorFileWriter,
                       QgsProject,
                       QgsCoordinateTransform,
                       QgsProcessingException,
                       QgsDataSourceUri,
                       QgsMapLayer,
                       QgsProviderRegistry,
                       QgsDataProvider,
                       QgsLayerTreeLayer
                        )
from datetime import datetime
from io import StringIO
import json
import os
import re
import shutil
import sqlite3
from pathlib import Path
from qgis.utils import iface
from osgeo import ogr


class AGS2DBAlgorithm(QgsProcessingAlgorithm):
    """
    This is an example algorithm that takes a vector layer and
    creates a new identical one.

    It is meant to be used as an example of how to create your own
    algorithms and explain methods and variables used to do it. An
    algorithm like this will be available in all elements, and there
    is not need for additional work.

    All Processing algorithms should extend the QgsProcessingAlgorithm
    class.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    OUTPUT = 'OUTPUT'
    OUTPUTFOLDER = 'OUTPUTFOLDER'
    SAMEFOLDER = 'SAMEFOLDER'
    INPUT = 'INPUT'
    CRS = 'CRS'
    QML = 'QML'
    BASEMAP = 'BASEMAP'
    GEOLOGYMAPS = 'GEOLOGYMAPS'
    USER = 'USER'

    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        # We add the input vector features source. It can have any kind of
        # geometry.


        self.addParameter(
            QgsProcessingParameterFile(
                self.INPUT,
                self.tr('Input File'),
                fileFilter='AGS (*.ags)'

            )
        )

        self.addParameter(
            QgsProcessingParameterFileDestination(
                self.OUTPUT,
                self.tr('Output File'),
                fileFilter='GeoPackage (*.gpkg);;SpatiaLite (*.sqlite)',
                optional = True

            )
        )

        self.addParameter(
            QgsProcessingParameterString(
                self.USER,
                self.tr('Initials or name of user, skip to use the system login name'),
                optional = True

            )
        )

        self.addParameter(
            QgsProcessingParameterCrs(
                self.CRS,
                'Coordinate Reference System',
                defaultValue=QgsCoordinateReferenceSystem('EPSG:27700')
            )
        )

        self.addParameter(
            QgsProcessingParameterFile(
                self.QML,
                self.tr('Style File'),
                fileFilter='QML (*.qml)',
                optional = True
            )
        )

        self.addParameter(
            QgsProcessingParameterBoolean(
                self.SAMEFOLDER,
                self.tr('Use same folder as AGS file'),
                defaultValue = True,
                optional = True
            )
        )

        # We add a feature sink in which to store our processed features (this
        # usually takes the form of a newly created vector layer when the
        # algorithm is run in QGIS).

        # self.addParameter(
            # QgsProcessingParameterFileDestination(
                # self.OUTPUTFOLDER,
                # self.tr('Output Folder')
            # )
        # )


        self.addParameter(
            QgsProcessingParameterBoolean(
                self.BASEMAP,
                self.tr('Include Google map basemap'),
                defaultValue = True,
                optional = False
            )
        )
        # list shown in dropdown in GUI
        self.mypredicatelist = [
                                '1m Lidar DTM',
                                'BGS Hydrogeology',
                                'Bedrock',
                                'Superficial deposits',
                                'Artificial ground',
                                'Mass movement',
                                'BGS Boreholes',
                                'BGS AGS Boreholes',
                                ]

        # self.mypredicatedefaultvalues = [2]
        self.addParameter(
            QgsProcessingParameterEnum(
            self.GEOLOGYMAPS,
            self.tr('Geology and DTM maps'),
            self.mypredicatelist,
            defaultValue = None, # self.mypredicatedefaultvalues,
            allowMultiple = True,
            optional = True
            )
        )


    def parse_ags_file(self, file_contents):

        def is_numeric(value):
            """Utility function to check if value can be converted to a number."""
            try:
                float(value)
                return True
            except ValueError:
                return False

        lines = file_contents.split('\n')
        data = {}
        current_group = None
        headers = []

        for line in lines:
            if not line.strip():
                continue

            temp = line.strip().split('","')
            temp = [item.strip('"') for item in temp]

            if temp[0] == 'GROUP':
                current_group = temp[1]
                data[current_group] = []  # Initialize the group
            elif temp[0] == 'HEADING':
                headers = temp[1:]
            elif temp[0] == 'UNIT':
                if current_group and headers:
                    unit_values = temp[1:]
                    # Pad missing values with empty strings
                    if len(unit_values) < len(headers):
                        unit_values.extend([''] * (len(headers) - len(unit_values)))
                    # Validate and skip invalid unit rows
                    if all(not value.strip() for value in unit_values):  # All empty or whitespace
                        continue
                    data[f"{current_group}_units"] = dict(zip(headers, unit_values))
            elif temp[0] == 'DATA':
                # Add data rows to the current group
                if current_group and headers:
                    record = dict(zip(headers, temp[1:]))
                    data[current_group].append(record)

        # Detect column types for each group independently
        column_types = {}
        for group_name, records in data.items():
            if group_name.endswith("_units"):
                continue

            if records:
                group_headers = list(records[0].keys())
                column_types[group_name] = {}
                for header in group_headers:
                    all_numeric = all(is_numeric(record.get(header)) for record in records if record.get(header))
                    column_types[group_name][header] = "REAL" if all_numeric else "TEXT"

        return data, column_types

    def createLOCAFeatures(self, records, column_types, crs, feedback):
        """
        Create a memory point layer for LOCA features using available coordinate fields.
        - Checks for LOCA_NATE/LOCA_NATN, LOCA_LOCX/LOCA_LOCY, LOCA_LAT/LOCA_LON in that order.
        - Logs if features or all fail to have coordinates.
        - Reprojects if using LAT/LON from EPSG:4326 to target CRS.
        """
        # Determine which coordinate fields are present and use them in priority:
        coord_priority = [
            ('LOCA_NATE', 'LOCA_NATN'),
            ('LOCA_LOCX', 'LOCA_LOCY'),
            ('LOCA_LAT', 'LOCA_LON')
        ]

        chosen_coords = None
        for pair in coord_priority:
            # Check if both fields exist
            if all(p in column_types['LOCA'] for p in pair):
                x_field, y_field = pair
                # Check if there's at least one record with non-empty coordinates
                has_data = False
                for record in records:
                    x_val = record.get(x_field)
                    y_val = record.get(y_field)
                    if x_val and x_val.strip() != '' and y_val and y_val.strip() != '':
                        has_data = True
                        break

                if has_data:
                    chosen_coords = pair
                    break

        # Create the layer
        layer = QgsVectorLayer("Point?crs={}".format(crs.authid()), "LOCA", "memory")
        data_provider = layer.dataProvider()

        # Add fields
        fields = QgsFields()
        for field_name, field_type in column_types['LOCA'].items():
            qgis_field_type = QVariant.Double if field_type == "REAL" else QVariant.String
            fields.append(QgsField(field_name, qgis_field_type))
        data_provider.addAttributes(fields)
        layer.updateFields()

        if chosen_coords is None:
            feedback.reportError("No recognized coordinate fields found in LOCA. Creating empty point layer.")
            return layer

        x_field, y_field = chosen_coords

        # Set up coordinate transform if needed
        # If we're using LAT/LON, we assume they're in EPSG:4326 and must transform to chosen CRS
        transform = None
        if chosen_coords == ('LOCA_LAT', 'LOCA_LON'):
            source_crs = QgsCoordinateReferenceSystem('EPSG:4326')
            transform = QgsCoordinateTransform(source_crs, crs, QgsProject.instance())

        features_with_coords = 0
        for record in records:
            # Get attributes
            attrs = []
            for header, ftype in column_types['LOCA'].items():
                val = record.get(header)
                if ftype == "REAL":
                    if val is None or val.strip() == '':
                        attrs.append(None)
                    else:
                        attrs.append(float(val))
                else:
                    attrs.append(val if val is not None else None)

            # Attempt to get coordinates
            x_val = record.get(x_field)
            y_val = record.get(y_field)
            if x_val is None or x_val.strip() == '' or y_val is None or y_val.strip() == '':
                # No coordinates for this feature
#                feedback.pushInfo(f"LOCA feature missing coordinates: {record}")
                # We still add the feature but without geometry

                f = QgsFeature()
                f.setAttributes(attrs)
                f.setGeometry(None)
                data_provider.addFeature(f)
                continue

            # Convert to float
            x = float(x_val)
            y = float(y_val)

            # Transform if LAT/LON
            if transform:
                pt = transform.transform(QgsPointXY(y, x))  # careful with order: LAT = Y, LON = X
            else:
                pt = QgsPointXY(x, y)

            f = QgsFeature()
            f.setAttributes(attrs)
            f.setGeometry(QgsGeometry.fromPointXY(pt))
            data_provider.addFeature(f)
            features_with_coords += 1

        layer.updateExtents()

        if features_with_coords == 0:
            feedback.reportError("No LOCA features had valid coordinates. The LOCA layer will have no geometries.")

        return layer

    def create_database_connection(self, gpkg_filepath, feedback):
        # Only works for gpkg
        md = QgsProviderRegistry.instance().providerMetadata("ogr")
        conn = md.createConnection(gpkg_filepath, {})
        conn_name = os.path.splitext(os.path.basename(gpkg_filepath))[0]
        md.saveConnection(conn, conn_name)
        # Refresh database connections in the Browser Panel
        iface.browserModel().reload()


    def add_meta_and_version_tables(self, ags_filepath, gpkg_filepath, user, feedback):
        """add new tables to help version control of data set
        As well as the table, the schema needs to be updated and
        it would be useful to add some data"""
        datetime_now = datetime.now()
        ags_file = Path(ags_filepath).stem

        create_cct_sql = ('CREATE TABLE "change_control" ( '
                            '"id"    INTEGER, '
                            '"description"   TEXT, '
                            '"purpose"   TEXT, '
                            '"datetime"  TEXT, '
                            '"authored_by"   TEXT, '
                            '"reviewed_by"   TEXT, '
                            'PRIMARY KEY("id" AUTOINCREMENT)'
                            ')')

        create_sdt_sql = ('CREATE TABLE "source_data" ( '
                            '"id"    INTEGER, '
                            '"ags_file_name" TEXT, '
                            '"geopackage_created_by" TEXT, '
                            '"geopackage_created_datetime"   TEXT, '
                            'PRIMARY KEY("id" AUTOINCREMENT)'
                            ')')

        cc_data_sql = 'INSERT INTO change_control values (?,?,?,?,?,?)'
        sd_data_sql = 'INSERT INTO source_data values (?,?,?,?)'

        try:
            with sqlite3.connect(gpkg_filepath) as conn:
                cursor = conn.cursor()
                cursor.execute(create_cct_sql)
                cursor.execute(create_sdt_sql)
            conn.commit()
            feedback.pushInfo("Added version control tables")
        except sqlite3.OperationalError as e:
            print(e)

        try:
            with sqlite3.connect(gpkg_filepath) as conn:
                cursor = conn.cursor()
                cursor.execute("INSERT INTO gpkg_contents (table_name, data_type, identifier, description, last_change, min_x, min_y, max_x, max_y, srs_id) VALUES('change_control', 'attributes', 'change_control', '', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 0, 0, 0, 0, 0);")
                cursor.execute("INSERT INTO gpkg_contents (table_name, data_type, identifier, description, last_change, min_x, min_y, max_x, max_y, srs_id) VALUES('source_data', 'attributes', 'source_data', '', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 0, 0, 0, 0, 0);")
                cursor.execute("INSERT INTO gpkg_ogr_contents (table_name, feature_count) VALUES('source_data', 1);")
                cursor.execute("INSERT INTO gpkg_ogr_contents (table_name, feature_count) VALUES('Change_control', 1);")
                feedback.pushInfo("contents1 done")
            conn.commit()
            feedback.pushInfo("Added data to contents")
        except sqlite3.OperationalError as e:
            print(e)

        try:
            with sqlite3.connect(gpkg_filepath) as conn:
                cursor = conn.cursor()
                cursor.execute(cc_data_sql,(0, "Initial creation", "For review", datetime_now, user, None))
                cursor.execute(sd_data_sql, (0, ags_file, user, datetime_now))
            conn.commit()
            feedback.pushInfo("Added data to version control tables")
        except sqlite3.OperationalError as e:
            print(e)

        conn.close()
        feedback.pushInfo("Control tables updated")

    def add_svg_paths(self, feedback):

        svg_path = os.path.join(os.path.dirname(__file__), 'styles', 'svg')
        svg_paths = QgsApplication.svgPaths()
        if svg_path not in svg_paths:
            svg_paths.append(svg_path)
            QgsApplication.setDefaultSvgPaths(svg_paths)
            feedback.pushInfo("Added custom SVG path for symbols.")

    # def loadLayerAndApplyStyle(self, output_path, table_name, qml_path, feedback):
        # # Load the layer using OGR provider. GPK and SpatiaLite are supported.

        # layer_path = f"{output_path}|layername={table_name}"
        # layer = QgsVectorLayer(layer_path, table_name, "ogr")

        # if not layer.isValid():
            # feedback.pushInfo(f"Table '{table_name}' cannot be added.")
            # return None

        # QgsProject.instance().addMapLayer(layer)
        # feedback.pushInfo(f"Added '{table_name}' layer to the project.")

        # if layer.isValid() and os.path.exists(qml_path):
            # layer.loadNamedStyle(qml_path)
            # layer.triggerRepaint()
            # feedback.pushInfo("Applied QML style to the LOCA layer.")

        # if iface:
            # iface.layerTreeView().refreshLayerSymbology(layer.id())

        # return layer


    def add_elev_calc_col(self, db_fpath: str, table_name: str, depth_col_names:list, feedback, col_name_loca_gl = 'LOCA_GL'):
        """adds calculated column (elevation) to existing table"""


        conn = sqlite3.connect(db_fpath)
        cursor = conn.cursor()
        cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
        listOfTables = list(list(zip(*cursor.fetchall()))[0])

        if table_name not in listOfTables:
            print(f"table {table_name} does not exist")
            conn.close()
            return None
        if table_name == 'LOCA':
            return None

        print(f"{table_name = }")

        qry_dict_loca = f"SELECT distinct lOCA_ID, LOCA_GL FROM LOCA;"
        cursor.execute(qry_dict_loca)
        dct_res_qry = dict(cursor.fetchall())

        filtered_dct_loca_gl = {loca_id: loca_gl for loca_id, loca_gl in dct_res_qry.items() if loca_gl != None}

        qry_lst_loca = f"SELECT distinct lOCA_ID FROM {table_name};"

        cursor.execute(qry_lst_loca)
        res_qry_list = list(list(zip(*cursor.fetchall()))[0])

        dct_filtered_data = {loca_id: filtered_dct_loca_gl[loca_id] for loca_id in res_qry_list if loca_id in filtered_dct_loca_gl}

        cursor.execute(f"ALTER TABLE {table_name} ADD COLUMN {col_name_loca_gl} REAL")

        for key, value in dct_filtered_data.items():
            qry = f"UPDATE {table_name} SET LOCA_GL = {value} WHERE LOCA_ID = '{key}';"
            cursor.execute(qry)

        for col_name in depth_col_names:
            print(f"{table_name = }")

            print(f"{col_name = }")
            try:
                cursor.execute(f"ALTER TABLE {table_name} ADD COLUMN ELEV_{col_name} REAL GENERATED ALWAYS AS ({col_name_loca_gl} - {col_name})")
            except:
                print(f"heading {col_name} not found")

        conn.commit()

        conn.close()

    def ApplyStyle(self, layer_name, qml_path, feedback):
        # Load the layer using OGR provider. GPK and SpatiaLite are supported.

        layer = QgsProject.instance().mapLayersByName(layer_name)

        try:
            if layer[0] and os.path.exists(qml_path):
                layer[0].loadNamedStyle(qml_path)
                layer[0].triggerRepaint()
                feedback.pushInfo("Applied QML style to the LOCA layer.")
        except:
                feedback.pushInfo("QML style failed to apply to the LOCA layer.")


    def load_all_layers(self, gpkg_path):
        # load all layers
        project = QgsProject.instance()

        layer = QgsVectorLayer(gpkg_path, "test", "ogr")
        subLayers = layer.dataProvider().subLayers()

        root = QgsProject.instance().layerTreeRoot()
        ags_fname = Path(gpkg_path).stem
        agsGroup = root.addGroup(ags_fname)



        for subLayer in subLayers:
            lyr_name = subLayer.split(QgsDataProvider.SUBLAYER_SEPARATOR)[1]
            uri = f"{gpkg_path}|layername={lyr_name}"
            # Create layer
            sub_vlayer = QgsVectorLayer(uri, lyr_name, 'ogr') # this is the place to map names if needed
            # Add layer to map in group))
            agsGroup.insertChildNode(-1,QgsLayerTreeLayer(QgsProject.instance().addMapLayer(sub_vlayer, False)))


    def copy_files(self, parameters, context, output_path, feedback):
        ags_file_path = self.parameterAsFile(parameters, self.INPUT, context)
        ags_file_stem = Path(ags_file_path).stem
        ags_parent = Path(ags_file_path).parents[0]
        # add date-time
        now = datetime.now()
        str_date_time = now.strftime("%m-%d-%H_%M")

        output_perm_folder = str(ags_parent) + "/" + str_date_time + "_" + ags_file_stem + '.gpkg'
        feedback.pushInfo(f"output_perm_folder: {output_perm_folder}")

        if self.parameterAsFile(parameters, self.SAMEFOLDER, context) == 'true':
            src = output_path
            dst = output_perm_folder
            feedback.pushInfo(f"source: {src}")
            feedback.pushInfo(f"dst: {dst}")
            # copy temp file to perm location
            shutil.copyfile(src, dst)
            feedback.pushInfo(f"file copied from: {src} to {dst}")
        return output_perm_folder


    def loadXYZ(self, url, name):
        rasterLyr = QgsRasterLayer("type=xyz&url=" + url, name, "wms")
        QgsProject.instance().addMapLayer(rasterLyr, False)
        # obtain the layer tree of the top-level group in the project
        layerTree = iface.layerTreeCanvasBridge().rootGroup()
        # the position is a number starting from 0, with -1 an alias for the end
        layerTree.insertChildNode(-1, QgsLayerTreeLayer(rasterLyr))


    def loadBGSwms(self, layer_index: int):
        """Plots a layer onto the map. Applies transparency to make it easier
        to read

        Parameters
        --------
        layer_index: int
            index of layer selected in list

        Returns
        --------
            BGS layer on map

        """

        lst_maps = ['Bedrock',
                    'Superficial deposits',
                    'Mass movement',
                    'Artificial ground']

        str_layer = self.mypredicatelist[layer_index]
        uri_layer = str_layer.replace(" ", ".") # required for url
        if str_layer == '1m Lidar DTM':
            urlWithParams = ("crs=EPSG:27700&dpiMode=7&featureCount=10&format=image/png&layers=Lidar_Composite_DTM_1m&styles&tilePixelRatio=0&url=https://environment.data.gov.uk/spatialdata/lidar-composite-digital-terrain-model-dtm-1m/wms?version%3D1.3.0")
        elif str_layer == 'BGS Hydrogeology':
            urlWithParams = ("crs=EPSG:27700&dpiMode=7&featureCount=10&format=image/png&layers=Hydrogeology&styles&tilePixelRatio=0&url=https://map.bgs.ac.uk/arcgis/services/GeoIndex_Onshore/hydrogeology/MapServer/WmsServer")
        elif str_layer in lst_maps:
            urlWithParams = (f"crs=EPSG:27700&dpiMode=7&featureCount=10&format=image/png&layers=BGS.50k.{uri_layer}&styles&tilePixelRatio=0&url=https://map.bgs.ac.uk/arcgis/services/BGS_Detailed_Geology/MapServer/WMSServer&http-header:referer=")
        elif str_layer == 'BGS AGS Boreholes':
            urlWithParams = ("crs=EPSG:27700&dpiMode=7&featureCount=10&format=image/png&layers=Boreholes&styles&tilePixelRatio=0&url=https://map.bgs.ac.uk/arcgis/services/AGS/AGS_Export/MapServer/WMSServer")
        elif str_layer == 'BGS Boreholes':
            urlWithParams = ("crs=EPSG:27700&dpiMode=7&featureCount=10&format=image/png&layers=Borehole.records&styles&tilePixelRatio=0&url=https://map.bgs.ac.uk/arcgis/services/GeoIndex_Onshore/boreholes/MapServer/WmsServer")


        rlayer = QgsRasterLayer(urlWithParams, str_layer, 'wms')
        if 'Boreholes' not in str_layer:
            rlayer.renderer().setOpacity(0.4)
        QgsProject.instance().addMapLayer(rlayer)


    def group_view(self, gpkg_path, view):
        name = Path(gpkg_path).stem
        root = QgsProject.instance().layerTreeRoot()
        group = root.findGroup(name)
        group.setExpanded(view)
        # clone the group
        cloned_group = group.clone()
        # move the node (along with sub-groups and layers) to the top
        root.insertChildNode(0, cloned_group)
        # remove the original node
        root.removeChildNode(group)


    def processAlgorithm(self, parameters, context, feedback):
        # Define the output path
        output_path = self.parameterAsFileOutput(parameters, self.OUTPUT, context)
        ext = os.path.splitext(output_path)[1].lower()
#        feedback.pushInfo(f"Writing all groups GeoPackage to: {output_path}")

        if self.parameterAsString(parameters, self.USER, context):
            user = self.parameterAsString(parameters, self.USER, context)
        else:
            user =os.getlogin( )

        # Remove existing GeoPackage if it exists
        if os.path.exists(output_path):
            os.remove(output_path)
#            feedback.pushInfo(f"Removed existing GeoPackage at: {output_path}")

        # Load AGS4 file contents
        ags_file_path = self.parameterAsFile(parameters, self.INPUT, context)
        with open(ags_file_path, 'r') as ags_file:
            file_contents = ags_file.read()

        # Get chosen CRS
        crs = self.parameterAsCrs(parameters, self.CRS, context)

        # Parse the AGS file
        data, column_types = self.parse_ags_file(file_contents)

        first_layer = True
        transform_context = context.transformContext()

        for group_name, records in data.items():
            if group_name.endswith("_units"):
                continue  # Skip unit tables

#            feedback.pushInfo(f"Processing group: {group_name}")

            if group_name.upper() == "LOCA":
                # Create spatial LOCA layer
                layer = self.createLOCAFeatures(records, column_types, crs, feedback)

            else:
                # Non-spatial layer
                layer = QgsVectorLayer("NoGeometry", group_name, "memory")
                data_provider = layer.dataProvider()

                # Add fields
                fields = QgsFields()
                for field_name, field_type in column_types[group_name].items():
                    qgis_field_type = QVariant.Double if field_type == "REAL" else QVariant.String
                    fields.append(QgsField(field_name, qgis_field_type))
                data_provider.addAttributes(fields)
                layer.updateFields()

                # Populate layer
                for record in records:
                    feature = QgsFeature()
                    attrs = []
                    for header, ftype in column_types[group_name].items():
                        val = record.get(header)
                        if ftype == "REAL":
                            if val is None or val.strip() == '':
                                attrs.append(None)
                            else:
                                attrs.append(float(val))
                        else:
                            attrs.append(val if val is not None else None)
                    feature.setAttributes(attrs)
                    data_provider.addFeature(feature)
                layer.updateExtents()

            # Export layer
            options = QgsVectorFileWriter.SaveVectorOptions()
            options.driverName = "GPKG"
            if ext == '.gpkg':
                options.driverName = "GPKG"
            elif ext == '.sqlite':
                options.driverName = "SQLite"
                options.driverOptions = ["SPATIALITE=YES"]
            else:
                raise QgsProcessingException("Unsupported file format selected.")

            options.layerName = group_name
            options.fileEncoding = "UTF-8"
            # Geometry type will be derived automatically for V3 method

            if first_layer:
                options.actionOnExistingFile = QgsVectorFileWriter.CreateOrOverwriteFile
            else:
                options.actionOnExistingFile = QgsVectorFileWriter.CreateOrOverwriteLayer

            error, newFilename, newLayer, errorMessage = QgsVectorFileWriter.writeAsVectorFormatV3(
                layer,
                output_path,
                transform_context,
                options
            )

            if error == QgsVectorFileWriter.NoError:
                feedback.pushInfo(f"Successfully transformed group '{group_name}' to GeoPackage.")
            else:
                feedback.reportError(f"Error transforming group '{group_name}' to GeoPackage: {errorMessage}")

            first_layer = False

        feedback.pushInfo("ALL GROUPS WRITTEN - DB CREATED")

        # add version control tables
        feedback.pushInfo("Adding version control tables")
        self.add_meta_and_version_tables(ags_file_path, output_path, user, feedback)
        feedback.pushInfo("Version control bales complete")

        # Add elevation data to tables
        feedback.pushInfo("Adding elevation data")
        json_data_path = os.path.join(os.path.dirname(__file__), 'data', 'elev_groups_heads.json')
        with open(json_data_path) as f:
            params = json.load(f)
        for key, value in params.items():
            self.add_elev_calc_col(output_path, key, value, feedback)
        feedback.pushInfo("Elevation data complete")

        # After the writing is done, call the helper functions:
        self.add_svg_paths(feedback)

        if self.parameterAsFile(parameters, self.QML, context) != '':
            qml_path = self.parameterAsFile(parameters, self.QML, context)
            feedback.pushInfo(f"{qml_path = }")
        else:
            qml_path = os.path.join(os.path.dirname(__file__), 'styles', 'loca_spatial.qml')
            feedback.pushInfo(f"{qml_path = }")
        # Create geology maps
        feedback.pushInfo(f"GEOLOGYMAPS: {self.parameterAsEnums(parameters, self.GEOLOGYMAPS, context)}")
        for index in self.parameterAsEnums(parameters, self.GEOLOGYMAPS, context):
            self.loadBGSwms(index)
        # create basemap
        if self.parameterAsFile(parameters, self.BASEMAP, context) == 'true':
            urlWithParams = 'https://tile.openstreetmap.org/{z}/{x}/{y}.png'
            self.loadXYZ(urlWithParams, 'Open Streetmap')

        # Copy the file from its temp location
        new_output_path = self.copy_files(parameters, context, output_path, feedback)
        self.create_database_connection(new_output_path, feedback)
        self.load_all_layers(new_output_path)
        self.ApplyStyle('LOCA', qml_path, feedback)
        self.group_view(new_output_path, False)
        proj = QgsProject.instance()
        proj.setCrs(QgsCoordinateReferenceSystem(27700))
        # zoom map to LOCA layer
        vlayer = QgsVectorLayer(new_output_path, "LOCA", "ogr")
        canvas = iface.mapCanvas()
        canvas.setExtent(vlayer.extent())
        canvas.refresh()

        return {self.OUTPUT: new_output_path}

    def processing_log(self, message):
        """
        Logs a message to the Processing log.
        """
        self.logMessage(message)

    def flags(self):
        return QgsProcessingAlgorithm.FlagNoThreading

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'AGS2DB'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return ''

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return AGS2DBAlgorithm()
