# -*- coding: utf-8 -*-
# TODO
# set titles for each graph
# safe plots to file

"""
/***************************************************************************
 ags_data_summary_plots
                                 A QGIS plugin
 AGS data summary plots
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-02-21
        copyright            : (C) 2026 by Amageo Limited
        email                : tony.daly@amageo.co.uk
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/

    This takes a Geopackage of AGS data and creates a series of summary plots,
    grouped by Geology Code. It is intended to be used as a quick way to
    visualise data, to spot any quality issues, but may be used in any way.
    It uses the Plotly library to create charts and tables. The output is a
    series of html files that the user saves to a directory. It also provides an
     immediate output to the default browser

    Useful future improvements:
    Allow the user to select other fields such as GEOL_GEOL2
    Add graphs and tables as required.
    Refactor once established.

"""

__author__ = 'Amageo Limited'
__date__ = '2026-02-21'
__copyright__ = '(C) 2026 by Amageo Limited'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import (QgsProcessing,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterEnum,
                       QgsProcessingParameterFeatureSink,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterFile,
                       QgsProcessingParameterFolderDestination)

from datetime import datetime
import math
import os
import sqlite3
import webbrowser

import numpy as np
import pandas as pd
import plotly.express as px
import plotly.io as pio



class ags_data_summary_plotsAlgorithm(QgsProcessingAlgorithm):
    """
    Inputs are designed to be simple, to make the process as
    easy as possible for the user.

    """

    OUTPUT = 'OUTPUT'
    INPUT = 'INPUT'
    LIST1 = 'LIST1'
    LIST2 = 'LIST2'
    STAGE_OPTIONS = ['Data quality review', 'Not for use in design',
                     'For use in design', 'For use in verification']
    STATUS_OPTIONS = ['Working draft', 'Draft for review', 'Final']

    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        # We add the input vector features source. It can have any kind of
        # geometry.
        self.addParameter(
            QgsProcessingParameterFile(
                self.INPUT,
                self.tr('GeoPackage file'),
                fileFilter='GeoPackage (*.gpkg)',
            )
        )
        self.addParameter(
            QgsProcessingParameterEnum(
                self.LIST1,
                self.tr("Information stage"),
                options=self.STAGE_OPTIONS,
                defaultValue=0
            )
        )
        self.addParameter(
            QgsProcessingParameterEnum(
                self.LIST2,
                self.tr("Status of output"),
                options=self.STATUS_OPTIONS,
                defaultValue=0
            )
        )
        # We add a feature sink in which to store our processed features (this
        # usually takes the form of a newly created vector layer when the
        # algorithm is run in QGIS).
        self.addParameter(
            QgsProcessingParameterFolderDestination(
                self.OUTPUT,
                self.tr('Output folder')
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        """
        The plots are currently in self-contained blocks of code due to the
         stage of development. It is likely that this function will be refactored.

        The following plots will be generated if the data is available:
        (update as necessary)
        1. SPT vs Depth
        2. SPT vs Elevation
        3. WC vs Depth
        4. WC distribution
        5. Undrained cohesion vs depth
        6. LL vs PI
        7. PSD
        8. Tables
           - Summary table of Geology by GEOL_GEOL
           - Table of all Samples and geology code
        """
        now = datetime.now()
        str_date_time =now.strftime("%Y-%m-%d %H:%M")
        database = parameters['INPUT']
        html_page_bg = '#d7eaf7'
        database_fname = os.path.basename(database)
        str_stage = self.STAGE_OPTIONS[self.parameterAsEnum(parameters,
                                                            self.LIST1, context)]
        str_status = self.STATUS_OPTIONS[self.parameterAsEnum(parameters,
                                                              self.LIST2, context)]
        def_graph_height = 650
        feedback.pushInfo(f"stage={str_stage}")
        feedback.pushInfo(f"status={str_status}")
        dst = parameters['OUTPUT']
        conn = sqlite3.connect(database)
        cur = conn.cursor()
        # get list and number of geol codes including blank
        feedback.pushInfo(f"Fetching geology codes.")
        try:
            cur.execute('select distinct GEOL_GEOL from GEOL')
            res = cur.fetchall()
            num_codes = len(res)
            lst_codes = []
            for code in res:
                lst_codes.append(code[0])

            feedback.pushInfo(f"List of unique geology codes = {lst_codes}")
        except:
            feedback.pushInfo(f"Cannot read the geology codes.")


        # fetch project details
        try:
            qry_proj = """select PROJ_NAME, PROJ_CLNT from PROJ"""
            cur.execute(qry_proj)
            res = cur.fetchone()
            proj_name = res[0]
            proj_clnt = res[1]
            feedback.pushInfo(f"Result={res}")
            # fetch file transmission details
            qry_tran = """select TRAN_PROD, TRAN_STAT, TRAN_DATE from TRAN"""
            cur.execute(qry_tran)
            res = cur.fetchone()
            tran_prod = res[0]
            tran_stat = res[1]
            tran_date = res[2]
            feedback.pushInfo(f"Result={res}")
            # create common metadata subtitle
            # use 'sup' because plotly version in QGIS does not support subtitle
            str_cht_meta = (f"<br><br><sup>Project Name: <b>{proj_name}</b><br> "
                            f"GeoPackage Filename: <b>{database_fname}</b> <br> "
                            f"Project stage/purpose: <b>{str_stage}</b> "
                            f"Chart status: <b>{str_status}</b> "
                            f"Date/time created: <b>{str_date_time}</b></sup>")

            title_hor_align = 0.5
            top_margin = 230
        except:
            feedback.pushInfo(f"Project and/or transmission details not in file.")



        # =================SPT -Depth==================================
        # create dataframe - link geology codes

        qry = """select ISPT.LOCA_ID, ISPT_TOP, ISPT_TOP+(cast(ISPT_NPEN as float)/1000) as ISPT_BASE,
                 ISPT_NVAL, ISPT_REP, GEOL_GEOL
                 from ISPT left join GEOL ON ISPT.LOCA_ID = GEOL.LOCA_ID
                 where ISPT_TOP >= GEOL_TOP AND ISPT_BASE <= GEOL.GEOL_BASE
                 order by GEOL_GEOL"""

        try:
            df = pd.read_sql_query(qry, conn)
            feedback.pushInfo(f"Result = {df}")
            num_codes = len(df['GEOL_GEOL'].unique())
            feedback.pushInfo(f"num_codes = {num_codes}")

            # need to plot nulls as 50 where non full penetration
            # reported result visble in hover
            df["ISPT_NVAL"] = df["ISPT_NVAL"].fillna(50)

            # create plot (matplotlib)
            pio.templates.default = "plotly_white"
            cols = 4
            graph_ht = 300+(math.ceil(num_codes/cols)*def_graph_height)

            # Create SPT vs depth multi plots
            fig = px.scatter(
                df,
                x='ISPT_NVAL',
                y='ISPT_TOP',
                height=graph_ht,
                facet_col='GEOL_GEOL',
                color='LOCA_ID',
                labels={"ISPT_NVAL": "SPT 'N' value",
                        "ISPT_TOP": "Depth (mbgl)",
                        "GEOL_GEOL": "Geology code",
                        "LOCA_ID": "EXPL Hole",
                        "ISPT_REP": "Reported value"
                        },

                hover_data=["ISPT_REP"],
                facet_col_wrap=cols
            )
            fig.update_layout(title_text=f"""<b>SPT vs Depth by geology code (GEOL_GEOL)</b>{str_cht_meta}""",
                              title_x = title_hor_align),
            fig.update_layout(margin_t=top_margin)
            fig.update_layout(xaxis_range=[0, 55])
            fig.update_layout(yaxis_range=[0, 35])
            fig.update_layout(showlegend=True)
            fig.update_xaxes(showgrid=True, gridwidth=1, gridcolor='DarkGray')
            fig.update_yaxes(showgrid=True, gridwidth=1, gridcolor='DarkGray')
            fig.update_traces(marker=dict(size=12,
                                          line=dict(width=2,
                                                    color='DarkSlateGrey')),
                              selector=dict(mode='markers'))
            fig.update_yaxes(autorange='reversed')
            fig.update_layout(paper_bgcolor=html_page_bg)
            fig.for_each_xaxis(lambda x: x.update(showticklabels=True))

            fig.write_html(dst+'/'+'SPTvsDepth.html')
            webbrowser.open_new_tab(dst+'/'+'SPTvsDepth.html')

        except:
            feedback.pushWarning(f"No SPT data to plot, output skipped")

        # =================SPT -Elevation==================================
        # create dataframe - link geology codes
        qry = """select SUB.LOCA_ID, ISPT_TOP, ISPT_BASE,
            ISPT_NVAL, ISPT_REP, GEOL_GEOL, (LOCA_GL - ISPT_TOP)
            as ISPT_ELEV, LOCA_GL
            from
            (select ISPT.LOCA_ID, ISPT_TOP, ISPT_TOP+(cast(ISPT_NPEN as float)/1000) as ISPT_BASE,
                 ISPT_NVAL, ISPT_REP, GEOL_GEOL
                 from ISPT left join GEOL ON ISPT.LOCA_ID = GEOL.LOCA_ID
                 where ISPT_TOP >= GEOL_TOP AND ISPT_BASE <= GEOL.GEOL_BASE) as SUB
            left join LOCA on SUB.LOCA_ID = LOCA.LOCA_ID
            order by GEOL_GEOL"""
        try:
            df = pd.read_sql_query(qry, conn)
            feedback.pushInfo(f"Result = {df}")
            num_codes = len(df['GEOL_GEOL'].unique())
            feedback.pushInfo(f"num_codes = {num_codes}")

            # Plot nulls as 50 where non full pen reported result visble in hover
            df["ISPT_NVAL"] = df["ISPT_NVAL"].fillna(50)

            # create plot (matplotlib)
            pio.templates.default = "plotly_white"
            cols = 4
            graph_ht = 300+(math.ceil(num_codes/cols)*def_graph_height)

            # Create SPT vs depth multi plots
            fig = px.scatter(
                df,
                x='ISPT_NVAL',
                y='ISPT_ELEV',
                height=graph_ht,
                facet_col='GEOL_GEOL',
                color='LOCA_ID',
                labels={"ISPT_NVAL": "SPT 'N' value",
                        "ISPT_ELEV": "Elevation (mAOD)",
                        "GEOL_GEOL": "Geology code",
                        "LOCA_ID": "EXPL Hole",
                        "ISPT_REP": "Reported value"
                        },
                hover_data=["ISPT_REP"],
                facet_col_wrap=4
                )
            fig.update_layout(title_text=f"""<b>SPT vs Elevation by geology code (GEOL_GEOL)</b>{str_cht_meta}""",
                              title_x = title_hor_align),
            fig.update_layout(margin_t=top_margin)
            fig.update_layout(xaxis_range=[0, 55])
            fig.update_layout(yaxis_range=[10, 60])
            fig.update_layout(showlegend=True)
            fig.update_xaxes(showgrid=True, gridwidth=1, gridcolor='DarkGray')
            fig.update_yaxes(showgrid=True, gridwidth=1, gridcolor='DarkGray')
            fig.update_traces(marker=dict(size=12,
                                          line=dict(width=2,
                                                    color='DarkSlateGrey')),
                              selector=dict(mode='markers'))
            fig.update_layout(paper_bgcolor=html_page_bg)
            fig.for_each_xaxis(lambda x: x.update(showticklabels=True))


            fig.write_html(dst+'/'+'SPTvsElevation.html')
            webbrowser.open_new_tab(dst+'/'+'SPTvsElevation.html')

        except:
            feedback.pushWarning(f"No SPT/elevation data to plot, output skipped")

        # ======================MOISTURE CONYENT vs Depth===========================

        # create dataframe - link geology codes
        qry = """select LNMC.LOCA_ID, SAMP_TOP, LNMC_MC, GEOL_GEOL
            from LNMC left join GEOL on LNMC.LOCA_ID = GEOL.LOCA_ID
            where SAMP_TOP >= GEOL_TOP and SAMP_TOP < GEOL_BASE
            order by GEOL_GEOL"""
        try:
            df = pd.read_sql_query(qry, conn)
            feedback.pushInfo(f"Result = {df}")
            num_codes = len(df['GEOL_GEOL'].unique())
            feedback.pushInfo(f"num_codes = {num_codes}")

            # create plot (matplotlib)
            pio.templates.default = "plotly_white"
            cols = 4
            graph_ht = 300+(math.ceil(num_codes/cols)*def_graph_height)

            # Create WC vs depth multi plots
            fig = px.scatter(
                df,
                x='LNMC_MC',
                y='SAMP_TOP',
                height=graph_ht,
                facet_col='GEOL_GEOL',
                color='LOCA_ID',
                labels={"LNMC_MC": "Water content(%)",
                        "SAMP_TOP": "Depth (mbgl)",
                        "GEOL_GEOL": "Geology code",
                        "LOCA_ID": "EXPL Hole"},

                facet_col_wrap=4
                )
            fig.update_layout(title_text=f"""<b>Water content vs Depth by geology code (GEOL_GEOL)</b>{str_cht_meta}""",
                              title_x = title_hor_align),
            fig.update_layout(margin_t=top_margin)
            fig.update_layout(xaxis_range=[0, 110])
            fig.update_layout(yaxis_range=[0, 35])
            fig.update_layout(showlegend=True)
            fig.update_xaxes(showgrid=True, gridwidth=1, gridcolor='DarkGray')
            fig.update_yaxes(showgrid=True, gridwidth=1, gridcolor='DarkGray')
            fig.update_traces(marker=dict(size=12,
                                          line=dict(width=2,
                                                    color='DarkSlateGrey')),
                              selector=dict(mode='markers'))
            fig.update_yaxes(autorange='reversed')
            fig.update_layout(paper_bgcolor=html_page_bg)
            fig.for_each_xaxis(lambda x: x.update(showticklabels=True))

            fig.write_html(dst+'/'+'WaterContentvsDepth.html')
            webbrowser.open_new_tab(dst+'/'+'WaterContentvsDepth.html')
        except:
            feedback.pushWarning(f"No water content data to plot, output skipped")


        # ======================MOISTURE CONTENT DIST=============================

        # create dataframe - link geology codes
        qry = """SELECT LNMC_MC, count(LNMC_MC) as count, GEOL_GEOL
            from (select LNMC.LOCA_ID, SAMP_TOP, LNMC_MC, GEOL_GEOL from LNMC
            left join GEOL on LNMC.LOCA_ID = GEOL.LOCA_ID
            where SAMP_TOP >= GEOL_TOP AND SAMP_TOP < GEOL_BASE)
            group by LNMC_MC, GEOL_GEOL order by GEOL_GEOL"""
        try:
            df = pd.read_sql_query(qry, conn)
            feedback.pushInfo(f"Result = {df}")
            num_codes = len(df['GEOL_GEOL'].unique())
            feedback.pushInfo(f"num_codes = {num_codes}")
            # create plot (matplotlib)
            pio.templates.default = "plotly_white"
            cols = 1
            if num_codes == 1:
                graph_ht = 300+(math.ceil(num_codes/cols)*(def_graph_height))
            else:
                graph_ht = 300+(math.ceil(num_codes/cols)*(def_graph_height)/1.5)

            # Create WC vs depth multi plots
            fig = px.bar(
                df,
                x='LNMC_MC',
                y='count',
                height=graph_ht,
                facet_row='GEOL_GEOL',
                color='GEOL_GEOL',
                labels={"LNMC_MC": "Water content(%)",
                        # "SAMP_TOP": "Depth (mbgl)",
                        "GEOL_GEOL": "Geology code",
                        # "LOCA_ID": "EXPL Hole"},
                        },
                facet_col_wrap=2
                )
            fig.update_layout(title_text=f"""<b>Water content distribution by geology code (GEOL_GEOL)</b>{str_cht_meta}""",
                              title_x = title_hor_align),
            fig.update_layout(margin_t=top_margin)
            fig.update_xaxes(showgrid=True, gridwidth=1, gridcolor='DarkGray')
            fig.update_yaxes(showgrid=True, gridwidth=1, gridcolor='DarkGray')
            # fig.update_traces(marker=dict(size=12,
            #                           line=dict(width=2,
            #                                     color='DarkSlateGrey')),
            #               selector=dict(mode='markers'))
            # fig.update_yaxes(autorange='reversed')
            fig.update_layout(paper_bgcolor=html_page_bg)
            fig.for_each_xaxis(lambda x: x.update(showticklabels=True))


            fig.write_html(dst+'/'+'WaterContentDist.html')
            webbrowser.open_new_tab(dst+'/'+'WaterContentDist.html')
        except:
            feedback.pushWarning(f"No water content data/elevation data to plot, output skipped")


        # =========================UNDRAINED COHESION vs Depth=====================

        # create dataframe - link geology codes
        qry = """select TRIT.LOCA_ID, SAMP_TOP, TRIT_CU, GEOL_GEOL
            from TRIT left join GEOL on TRIT.LOCA_ID = GEOL.LOCA_ID
            where SAMP_TOP >= GEOL_TOP and SAMP_TOP < GEOL_BASE
            order by GEOL_GEOL"""
        try:
            df = pd.read_sql_query(qry, conn)
            feedback.pushInfo(f"Result = {df}")
            num_codes = len(df['GEOL_GEOL'].unique())
            feedback.pushInfo(f"num_codes = {num_codes}")

            # create plot (matplotlib)
            pio.templates.default = "plotly_white"
            cols = 4
            graph_ht = 300+(math.ceil(num_codes/cols)*def_graph_height)

            # Create WC vs depth multi plots
            fig = px.scatter(
                df,
                x='TRIT_CU',
                y='SAMP_TOP',
                height=graph_ht,
                facet_col='GEOL_GEOL',
                color='LOCA_ID',
                labels={"TRIT_CU": "Undrained Cohesion (kN/m<sup>2</sup>)",
                        "SAMP_TOP": "Depth (mbgl)",
                        "GEOL_GEOL": "Geology code",
                        "LOCA_ID": "EXPL Hole"},
                facet_col_wrap=4
                )
            fig.update_layout(title_text=f"""<b>Undrained cohesion vs Depth by geology code (GEOL_GEOL)</b>{str_cht_meta}""",
                              title_x = title_hor_align),
            fig.update_layout(margin_t=top_margin)
            fig.update_layout(xaxis_range=[0, 400])
            fig.update_layout(yaxis_range=[0, 35])
            fig.update_layout(showlegend=True)
            fig.update_xaxes(showgrid=True, gridwidth=1, gridcolor='DarkGray')
            fig.update_yaxes(showgrid=True, gridwidth=1, gridcolor='DarkGray')
            fig.update_traces(marker=dict(size=12,
                                          line=dict(width=2,
                                                    color='DarkSlateGrey')),
                              selector=dict(mode='markers'))
            fig.update_yaxes(autorange='reversed')
            fig.update_layout(paper_bgcolor=html_page_bg)
            fig.for_each_xaxis(lambda x: x.update(showticklabels=True))

            fig.write_html(dst+'/'+'UndrainedCohesionvsDepth.html')
            webbrowser.open_new_tab(dst+'/'+'UndrainedCohesionvsDepth.html')
        except:
            feedback.pushWarning(f"No undrained cohesion data to plot, output skipped")

        # =========================PLASTICITY=====================

        # create dataframe - link geology codes
        qry = """select LLPL.LOCA_ID, SAMP_TOP, LLPL_LL, LLPL_PL,
            (LLPL_LL-LLPL_PL) as IP, GEOL_GEOL from LLPL left join GEOL
            on LLPL.LOCA_ID = GEOL.LOCA_ID
            where SAMP_TOP >= GEOL_TOP AND SAMP_TOP < GEOL_BASE
            order by GEOL_GEOL"""
        try:
            df = pd.read_sql_query(qry, conn)
            feedback.pushInfo(f"Result = {df}")
            num_codes = len(df['GEOL_GEOL'].unique())
            feedback.pushInfo(f"num_codes = {num_codes}")
            lst_GEOL_GEOL = df['GEOL_GEOL'].unique()

            # create plot (matplotlib)
            pio.templates.default = "plotly_white"
            cols = 1
            if num_codes == 1:
                graph_ht = 300+(math.ceil(num_codes/cols)*(def_graph_height))
            else:
                graph_ht = 300+(math.ceil(num_codes/cols)*(def_graph_height)/1.5)

            # Create WC vs depth multi plots
            fig = px.scatter(
                df,
                x='LLPL_LL',
                y='IP',
                height=graph_ht,
                facet_row='GEOL_GEOL',
                color='LOCA_ID',
                labels={"LLPL_LL": "Liquid Limit (%)",
                        "LLPL_PL": "Plastic Limit (%)",
                        "IP": "Plasticity Index (%)",
                        "GEOL_GEOL": "Code",
                        "LOCA_ID": "EXPL Hole"},
                hover_data=["LLPL_PL"],
                )
            col = 1
            for row in range(1, len(lst_GEOL_GEOL)+1):
                feedback.pushInfo(f"Row = {row}")


                fig.add_annotation(x=37, y=17, text='CL or OL',
                                   xref=f'x{col}', yref=f'y{row}', showarrow=False)
                fig.add_annotation(x=63, y=43, text='CH or OH',
                                   xref=f'x{col}', yref=f'y{row}', showarrow=False)
                fig.add_annotation(x=40, y=7, text='ML or OL',
                                   xref=f'x{col}', yref=f'y{row}', showarrow=False)
                fig.add_annotation(x=70, y=23, text='MH or OH',
                                   xref=f'x{col}', yref=f'y{row}', showarrow=False)
                fig.add_annotation(x=16, y=5.5, text='CL or ML',
                                   xref=f'x{col}', yref=f'y{row}', showarrow=False)

                # A line
                fig.add_shape(type="line", x0=25.5, x1=102, y0=4, y1=60,
                              xref=f'x{col}', yref=f'y{row}',
                              line=dict(color="black", width=1))
                # max line
                fig.add_shape(type="line", x0=0, x1=60, y0=0, y1=60,
                              xref=f'x{col}', yref=f'y{row}',
                              line=dict(color="black", width=1))

                # U Line
                fig.add_shape(type="line", x0=16, x1=16, y0=0, y1=7,
                              xref=f'x{col}', yref=f'y{row}',
                              line=dict(color="black", width=1, dash="dash"))
                fig.add_shape(type="line", x0=16, x1=73, y0=7, y1=60,
                              xref=f'x{col}', yref=f'y{row}',
                              line=dict(color="black", width=1, dash="dash"))

                # CL ML box
                fig.add_shape(type="line", x0=4, x1=25.5, y0=4, y1=4,
                              xref=f'x{col}', yref=f'y{row}',
                              line=dict(color="black", width=1))
                fig.add_shape(type="line", x0=7, x1=29.5, y0=7, y1=7,
                              xref=f'x{col}', yref=f'y{row}',
                              line=dict(color="black", width=1))

                # LL line
                fig.add_shape(type="line", x0=50, x1=50, y0=0, y1=60,
                              xref=f'x{col}', yref=f'y{row}',
                              line=dict(color="black", width=1))

            fig.update_layout(title_text=f"""<b>Plasticity by geology code (GEOL_GEOL)</b>{str_cht_meta}""",
                              title_x = title_hor_align),
            fig.update_layout(margin_t=top_margin)
            fig.update_layout(xaxis_range=[0, 110])
            fig.update_layout(yaxis_range=[0, 60])
            fig.update_layout(showlegend=True)
            fig.update_xaxes(showgrid=True, gridwidth=1, gridcolor='DarkGray')
            fig.update_yaxes(showgrid=True, gridwidth=1, gridcolor='DarkGray')
            fig.update_traces(marker=dict(size=12,
                                          line=dict(width=2,
                                                    color='DarkSlateGrey')),
                              selector=dict(mode='markers'))
            fig.update_layout(paper_bgcolor=html_page_bg)
            fig.for_each_xaxis(lambda x: x.update(showticklabels=True))

            fig.write_html(dst+'/'+'PlasticityIndex.html')
            webbrowser.open_new_tab(dst+'/'+'PlasticityIndex.html')
        except:
            feedback.pushWarning(f"No plasticity data to plot, output skipped")

            # =========================GRADING=====================

        # create dataframe - link geology codes
        qry = """select GRAT.LOCA_ID, GRAT.SAMP_TOP, SAMP_TYPE, GRAT_SIZE,
            GRAT_PERP, GEOL_GEOL
            from GRAT left join GEOL ON GRAT.LOCA_ID = GEOL.LOCA_ID
            where SAMP_TOP >= GEOL_TOP and SAMP_TOP < GEOL_BASE
            order by GEOL_GEOL"""
        try:
            df = pd.read_sql_query(qry, conn)
            feedback.pushInfo(f"Result = {df}")
            num_codes = len(df['GEOL_GEOL'].unique())
            feedback.pushInfo(f"num_codes = {num_codes}")
            cols = 1
            if num_codes == 1:
                graph_ht = 300+(math.ceil(num_codes/cols)*(def_graph_height))
            else:
                graph_ht = 300+(math.ceil(num_codes/cols)*(def_graph_height)/1.2)


            lst_GEOL_GEOL = df['GEOL_GEOL'].unique()

            pio.templates.default = "plotly_white"

            # Create WC vs depth multi plots
            fig = px.line(
            df,
            x='GRAT_SIZE',
            y='GRAT_PERP',
            log_x=True,
            range_x=[0.001,200],
            range_y=[0,100],
            height = graph_ht,
            facet_row = 'GEOL_GEOL',
            color = 'LOCA_ID',
            symbol = 'SAMP_TOP',
            labels={"GRAT_SIZE": "Particle size diameter (mm)",
                    "GRAT_PERP": "Percent passing (%)",
                    "GEOL_GEOL": "Code",
                    "LOCA_ID": "EXPL Hole",
                    "SAMP_TYPE":"Sample Type"},
            markers=True,
            hover_data=["SAMP_TYPE"],
            )
            col = 1
            for row in range(1, len(lst_GEOL_GEOL)+1):
                # feedback.pushInfo(f"Row = {row}")
                # Major divisions
                fig.add_shape(type="line", x0=0.002, x1=0.002, y0=0, y1=100,
                              xref=f'x{col}', yref=f'y{row}',
                              line=dict(color="black", width=2))
                fig.add_shape(type="line", x0=0.06, x1=0.06, y0=0, y1=100,
                              xref=f'x{col}', yref=f'y{row}',
                              line=dict(color="black", width=2))
                fig.add_shape(type="line", x0=2, x1=2, y0=0, y1=100,
                              xref=f'x{col}', yref=f'y{row}',
                              line=dict(color="black", width=2))
                fig.add_shape(type="line", x0=60, x1=60, y0=0, y1=100,
                              xref=f'x{col}', yref=f'y{row}',
                              line=dict(color="black", width=2))
                #Minor divisions
                fig.add_shape(type="line", x0=0.006, x1=0.006, y0=0, y1=100,
                              xref=f'x{col}', yref=f'y{row}',
                              line=dict(color="black", width=1.5, dash="dash"))
                fig.add_shape(type="line", x0=0.02, x1=0.02, y0=0, y1=100,
                              xref=f'x{col}', yref=f'y{row}',
                              line=dict(color="black", width=1.5, dash="dash"))
                fig.add_shape(type="line", x0=0.2, x1=0.2, y0=0, y1=100,
                              xref=f'x{col}', yref=f'y{row}',
                              line=dict(color="black", width=1.5, dash="dash"))
                fig.add_shape(type="line", x0=0.6, x1=0.6, y0=0, y1=100,
                              xref=f'x{col}', yref=f'y{row}',
                              line=dict(color="black", width=1.5, dash="dash"))
                fig.add_shape(type="line", x0=6, x1=6, y0=0, y1=100,
                              xref=f'x{col}', yref=f'y{row}',
                              line=dict(color="black", width=1.5, dash="dash"))
                fig.add_shape(type="line", x0=20, x1=20, y0=0, y1=100,
                              xref=f'x{col}', yref=f'y{row}',
                              line=dict(color="black", width=1.5, dash="dash"))


            # fig.update_layout(xaxis_range=[0.001,2])
            # fig.update_layout(yaxis_range=[0,100])
            fig.update_layout(title_text=f"""<b>Particle size distribution by geology code (GEOL_GEOL)</b>{str_cht_meta}""",
                              title_x = title_hor_align),
            fig.update_layout(margin_t=top_margin)
            fig.update_layout(showlegend=True)
            fig.update_xaxes(showgrid=True, gridwidth=1, gridcolor='DarkGray')
            fig.update_yaxes(showgrid=True, gridwidth=1, gridcolor='DarkGray')
            fig.update_traces(marker=dict(size=4,
                                      line=dict(width=2,
                                                color='DarkSlateGrey')),
                          selector=dict(mode='markers'))
            fig.update_layout(paper_bgcolor=html_page_bg)
            fig.for_each_xaxis(lambda x: x.update(showticklabels=True))

            fig.write_html(dst+'/'+'ParticleSizeDistribution.html')
            webbrowser.open_new_tab(dst+'/'+'ParticleSizeDistribution.html')
        except:
            feedback.pushWarning(f"No PSD data data to plot, output skipped")

        # ========data tables===========

        lst_tables =[]
        lst_table_titles =[]

        #==========Table 1==========
        try:
            table_title = "Table 1: Geology code and exloratory hole min and max summary"
            qry = """select GEOL_GEOL, ABBR.ABBR_DESC, min(GEOL_TOP) as [minimum top depth],
            max(GEOL_TOP) as [maximum top depth], min(GEOL_BASE) as
            [minimum base depth], max(GEOL_BASE) as [maximum base depth]
            from GEOL join ABBR on GEOL.GEOL_GEOL = ABBR.ABBR_CODE
            where ABBR_HDNG = 'GEOL_GEOL' group by GEOL_GEOL order by GEOL_GEOL"""
            df = pd.read_sql_query(qry, conn)
            df = df.replace(np.nan, "-")
            html_table = df.to_html(index=False)

            lst_tables.append('<h3 id="'+table_title+'">'+ table_title +'</h3>'+ html_table)
            lst_table_titles.append(table_title)
        except:
            feedback.pushWarning(f"Summary table of Geology by GEOL_GEOL skipped")

        #==========Table 2==========
        try:
            table_title = 'Table2:  Geology codes and associated exploratory holes'
            qry = 'select distinct LOCA_ID, GEOL_GEOL from GEOL where length(GEOL_GEOL) > 0 '
            df = pd.read_sql_query(qry, conn)
            lst_codes = df['GEOL_GEOL'].unique()
            dct_1 = {'GEOL_GEOL':lst_codes}
            lst_code_loc =[]
            dct_code_loc = {}
            for code in lst_codes:
                df1 = df.loc[df['GEOL_GEOL'] == code]
                lst_loca_id = list(df1['LOCA_ID'])
                lst_code_loc.append(lst_loca_id)
            dct_2 = {'Hole List':lst_code_loc}
            dct_code_loc.update(dct_1)
            dct_code_loc.update(dct_2)
            df = pd.DataFrame(dct_code_loc)
            df = df.sort_values(by=['GEOL_GEOL'])
            html_table = df.to_html(index=False)

            lst_tables.append('<h3 id="'+table_title+'">'+ table_title +'</h3>'+ html_table)
            lst_table_titles.append(table_title)
        except:
            feedback.pushWarning(f"Summary table Geology codes and exploratory holes skipped")

        #==========Table 3==========
        try:
            table_title = "Table 3: Missing geology codes (GEOL_GEOL)"
            qry = """select LOCA_ID, GEOL_TOP, GEOL_BASE, GEOL_GEOL from GEOL where length(GEOL_GEOL) = 0"""

            df = pd.read_sql_query(qry, conn)
            df = df.replace(np.nan, "-")
            html_table = df.to_html(index=False)

            lst_tables.append('<h3 id="'+table_title+'">'+ table_title +'</h3>'+ html_table)
            lst_table_titles.append(table_title)
        except:
            feedback.pushWarning(f"Table of all Samples and geology code")
        #==========Table 4==========
        try:
            table_title = "Table 4: Samples and associated geology code"
            qry = """select SAMP.LOCA_ID, SAMP_TOP, SAMP_BASE, SAMP_TYPE, SAMP_REF,
            SAMP_CONT, SAMP_RECV, SAMP_CLSS, SAMP_DESC, GEOL_GEOL from SAMP
            left join GEOL on SAMP.LOCA_ID = GEOL.LOCA_ID
            where SAMP_TOP >= GEOL_TOP AND SAMP_TOP < GEOL_BASE"""

            df = pd.read_sql_query(qry, conn)
            df = df.replace(np.nan, "-")
            html_table = df.to_html(index=False)

            lst_tables.append('<h3 id="'+table_title+'">'+ table_title +'</h3>'+ html_table)
            lst_table_titles.append(table_title)
        except:
            feedback.pushWarning(f"Table of all Samples and geology code")

        #======compile html page=============
        try:
            str_table_body = ''
            str_table_start = "<p><ul>"
            str_table_end = "</ul></p>"
            for table in lst_table_titles:
                str_table_item = f'<li><a href="#{table}">{table}</a></li>'
                str_table_body = str_table_body + str_table_item

            str_table_list = str_table_start + str_table_body + str_table_end

            str_tables = '+'.join(lst_tables)

            html_content = ("<p>" + str_cht_meta + "</p>"\
                            + str_table_list + \
                            str_tables
                            )

            html_header = """   <!DOCTYPE html>
                                <html>
                                <head>
                                <style>
                                *
                                {
                                   font-size: 1em !important;
                                   font-family: Arial !important;
                                }
                                p {text-align: center;
                                   color: midnightblue;
                                   }
                                body {
                                background-color: RGB(215,234,247);
                                    }
                                table {
                                  border-collapse: collapse;
                                }
                                th, td {
                                  padding: 7.5px;
                                  text-align: left;
                                  border: 1px solid #9a9996;
                                }
                                thead tr {background-color: #1c71d8; color:#FFF;}
                                tbody tr:nth-child(odd) {background-color: #FFF;}
                                tbody tr:nth-child(even) {background-color: #EAEAEA;}
                                </style>
                                </head>
                                <body>"""

            html_footer = """</body>
                             </html>"""

            with open(dst+'/'+'tables.html', 'w') as f:
                f.write(html_header)
            with open(dst+'/'+'tables.html', 'a') as f:
                f.write(html_content)
                f.write(html_footer)
            webbrowser.open_new_tab(dst+'/'+'tables.html')
        except:
            feedback.pushWarning(f"Error creating summary table output.")

        conn.close()

        # End loop
        # TODO save database with plots for completeness?

        if feedback.isCanceled():
            return {}

        return {}

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'AGS Summary Plots'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'AGS data visualisation'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return ags_data_summary_plotsAlgorithm()
